Add feedback form with pop-up messages
Valeria310/MyGreenApp pull request #53
Opened 2023-09-23 21:53 UTC by fstk1337

2023-09-25 13:59 UTC, alekseirechitskiy approved these changes
OK

2023-09-29 13:08 UTC, Valeria310 commented on src/components/ContactButton/ContactButton.module.scss
кнопка не должна пропадать внизу страницы, см. документацию

2023-09-29 13:36 UTC, Valeria310 commented on src/components/Parallax/Parallax.scss
не надо без веской причины менять чужие компоненты!

2023-09-29 13:38 UTC, Valeria310 commented on src/components/Ticker/Ticker.module.scss
закомментированные стили, как и код тоже не надо оставлять, тем более в чужом компоненте!

2023-09-29 13:43 UTC, Valeria310 requested changes
необходимо исправить замечания

2023-09-29 14:09 UTC, fstk1337 commented on src/components/Parallax/Parallax.scss
причины имеются.

2023-09-29 14:16 UTC, fstk1337 commented on src/components/Ticker/Ticker.module.scss
первый раз слышу про "чужие" компоненты.

2023-10-07 12:28 UTC, fstk1337 commented on src/components/ContactButton/ContactButton.module.scss
исправлено

2023-10-16 12:59 UTC, andreikostsen approved these changes
Мне все нравится! Зачет!

2023-10-21 08:02 UTC, merged